feat: change to self iteration build

diff --git a/.github/workflows/status check.yml b/.github/workflows/status check.yml
--- a/.github/workflows/status check.yml
+++ b/.github/workflows/status check.yml
@@ -24,15 +24,10 @@ jobs:
           echo "projects=$(echo $projects | jq -R 'split(" ")' -c)" >> $GITHUB_OUTPUT
           echo "Found projects: $(echo $projects | jq -R 'split(" ")' -c)"
 
-  build-check:
+  build-all:
     needs: find-projects
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        project: ${{ fromJson(needs.find-projects.outputs.projects) }}
-      fail-fast: false
     name: build
-
     steps:
       - uses: actions/checkout@v3
 
@@ -42,9 +37,39 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Make gradlew executable
-        run: chmod +x ./project/${{ matrix.project }}/gradlew
+      - name: Get all projects
+        run: |
+          echo "Building projects:"
+          echo '${{ needs.find-projects.outputs.projects }}'
 
-      - name: Build with Gradle
-        working-directory: ./project/${{ matrix.project }}
-        run: ./gradlew clean build
+      - name: Make all gradlew files executable
+        run: |
+          for project in $(echo '${{ needs.find-projects.outputs.projects }}' | jq -r '.[]'); do
+            echo "Making gradlew executable for $project"
+            chmod +x ./project/$project/gradlew
+          done
+
+      - name: Build all projects
+        id: build
+        run: |
+          success=true
+          failed_projects=()
+          
+          for project in $(echo '${{ needs.find-projects.outputs.projects }}' | jq -r '.[]'); do
+            echo "Building $project..."
+          
+            cd $GITHUB_WORKSPACE/project/$project
+            if ./gradlew clean build; then
+              echo "✅ Build succeeded for $project"
+            else
+              echo "❌ Build failed for $project"
+              failed_projects+=("$project")
+              success=false
+            fi
+            cd $GITHUB_WORKSPACE
+          done
+          
+          if [ "$success" = false ]; then
+            echo "::error::Failed projects: ${failed_projects[@]}"
+            exit 1
+          fi
